### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by ravellaabhinav** [Sharan312/Airline-rreservation-System#1]
Hey did you rectift it

**Comment by Sharan312** [comment]
download this project and tryout: https://github.com/Sharan312/Airline-rreservation-System

**Comment by ravellaabhinav** [comment]
How to configure sql

**Comment by ravellaabhinav** [comment]
It's using xampp sever and phpmyadmin right??

**Comment by Sharan312** [comment]
yes

**Comment by ravellaabhinav** [comment]
Is it enough to import .sql file and run the code
or else i need to edit the code

**Comment by Sharan312** [comment]
import the SQL file in PHPMyAdmin it will execute automatically
